# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c88e5cc12255d359e5214b5f53ffdb10a5dcef5392e01f09694915f992c2f822604e93000e87dcc763c97c1e44717e1a9d5254b478221990154bb196d70d61

test:
  secret_key_base: cd136e14cddd8b73f4be562e8870a7ee6f13914e315cdcdc6fb5bf4be4e530ed575a256fefb32d52072708046a6722f98d325ab9e5175da639c3e21868c49042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
